### ISSUE TITLE
编译后ddns选项里并没有dnspod可选

### ISSUE THREAD

**Issue by VergilGao** [small-5/ddns-scripts-dnspod#1]
是因为makefile里面没有写postinst控制项吗？
对比了一下lean仓库里的源码和这个仓库的源码，我觉得应该就是这个原因，postinst脚本在deb包里是安装后初始化配置文件用的，在openwrt的apk里应该也是类似的功能吧。

**Comment by small-5** [comment]
回退 9660f683d8398c49049e1b621b0ae4aa64482883 這個commit，就可以在19.07上使用了

**Comment by VergilGao** [comment]
> 回退 [9660f68](https://github.com/small-5/ddns-scripts-dnspod/commit/9660f683d8398c49049e1b621b0ae4aa64482883) 這個commit，就可以在19.07上使用了

感谢。

**Comment by VergilGao** [comment]
希望能增加一个19.07分支来让其他使用19.07.x的人可以更方便的克隆源码编译。
当然这是一个建议。
我自己fork了一份源码并创建了19.07分支。

**Comment by small-5** [comment]
現在19.07已經沒什麼人用了。。。

**Comment by VergilGao** [comment]
毕竟是stable版，只要社区还在打安全补丁肯定还是有人用的啊。

**Comment by small-5** [comment]
明天有空再弄吧。那就給19.07單純做一個出來

**Comment by small-5** [comment]
明天有空再弄吧。那就給19.07單獨弄一個分支出來

**Comment by VergilGao** [comment]
嗯，其实蛮简单的，本地新建一个分支，然后回退。
最后
```git push --set-upstream origin 19.07```
就可以直接在github上多出来一个19.07分支了。
